# -*- coding: utf-8 -*-
"""run_attn_pats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gY8PUf-ilXOy6BEGKXQbe5G2Mw99AdT1

# Setup

## Install and Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install git+https://github.com/neelnanda-io/TransformerLens.git

"""## Import functions from repo"""

# %cd ..
# !rm -rf seqcont_circ_expms

!git clone https://github.com/wlg1/seqcont_circ_expms.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/seqcont_circ_expms/src/attn_pats

"""# Run script

When you run a script using !python, you're essentially starting a new Python interpreter on top of the one that's already running your notebook. This additional interpreter can consume extra memory, potentially leading to OOM errors, especially if your script is memory-intensive.
"""

!python run_attn_pats.py --model "gpt2" --task "numerals" --num_samps 128

